// <auto-generated />
using System;
using Eagle.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Eagle.Data.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20240824183007_new7")]
    partial class new7
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Eagle.Models.Company", b =>
                {
                    b.Property<int>("CompanyId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CompanyId"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.HasKey("CompanyId");

                    b.ToTable("tblCompany");

                    b.HasData(
                        new
                        {
                            CompanyId = 1,
                            Email = "Dalas@gmail.com",
                            Location = "Amman",
                            Name = "Dalas",
                            Phone = "0775426229"
                        },
                        new
                        {
                            CompanyId = 2,
                            Email = "Moakeb@gmail.com",
                            Location = "Amman",
                            Name = "Moakeb",
                            Phone = "0775422429"
                        },
                        new
                        {
                            CompanyId = 3,
                            Email = "Petra@gmail.com",
                            Location = "Amman",
                            Name = "Petra",
                            Phone = "0791122429"
                        });
                });

            modelBuilder.Entity("Eagle.Models.Section", b =>
                {
                    b.Property<int>("SectionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SectionId"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("SectionId");

                    b.ToTable("tblSection");

                    b.HasData(
                        new
                        {
                            SectionId = 1,
                            Name = "Air Flight"
                        },
                        new
                        {
                            SectionId = 2,
                            Name = "Land Trip"
                        },
                        new
                        {
                            SectionId = 3,
                            Name = "Cruise"
                        });
                });

            modelBuilder.Entity("Eagle.Models.Trip", b =>
                {
                    b.Property<int>("TripId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TripId"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateOnly>("EndDate")
                        .HasColumnType("date");

                    b.Property<TimeOnly>("EndTime")
                        .HasColumnType("time");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<double>("Price")
                        .HasColumnType("float");

                    b.Property<int>("SectionId")
                        .HasColumnType("int");

                    b.Property<DateOnly>("StartDate")
                        .HasColumnType("date");

                    b.Property<TimeOnly>("StartTime")
                        .HasColumnType("time");

                    b.HasKey("TripId");

                    b.HasIndex("SectionId");

                    b.ToTable("tblTrip");

                    b.HasData(
                        new
                        {
                            TripId = 1,
                            Description = "Palastine",
                            EndDate = new DateOnly(2024, 8, 24),
                            EndTime = new TimeOnly(23, 30, 6, 691).Add(TimeSpan.FromTicks(51)),
                            Name = "Jordan",
                            Price = 150.0,
                            SectionId = 1,
                            StartDate = new DateOnly(2024, 8, 19),
                            StartTime = new TimeOnly(16, 30, 6, 691).Add(TimeSpan.FromTicks(46))
                        },
                        new
                        {
                            TripId = 2,
                            Description = "Turky",
                            EndDate = new DateOnly(2024, 8, 24),
                            EndTime = new TimeOnly(23, 30, 6, 691).Add(TimeSpan.FromTicks(55)),
                            Name = "Jordan",
                            Price = 450.0,
                            SectionId = 1,
                            StartDate = new DateOnly(2024, 8, 22),
                            StartTime = new TimeOnly(19, 30, 6, 691).Add(TimeSpan.FromTicks(55))
                        },
                        new
                        {
                            TripId = 3,
                            Description = "Canada",
                            EndDate = new DateOnly(2024, 8, 24),
                            EndTime = new TimeOnly(6, 30, 6, 691).Add(TimeSpan.FromTicks(59)),
                            Name = "Jordan",
                            Price = 650.0,
                            SectionId = 1,
                            StartDate = new DateOnly(2024, 8, 15),
                            StartTime = new TimeOnly(22, 30, 6, 691).Add(TimeSpan.FromTicks(58))
                        },
                        new
                        {
                            TripId = 4,
                            Description = "Iraq",
                            EndDate = new DateOnly(2024, 8, 24),
                            EndTime = new TimeOnly(23, 30, 6, 691).Add(TimeSpan.FromTicks(63)),
                            Name = "Jordan",
                            Price = 150.0,
                            SectionId = 2,
                            StartDate = new DateOnly(2024, 8, 19),
                            StartTime = new TimeOnly(16, 30, 6, 691).Add(TimeSpan.FromTicks(62))
                        },
                        new
                        {
                            TripId = 5,
                            Description = "Palastine",
                            EndDate = new DateOnly(2024, 8, 24),
                            EndTime = new TimeOnly(23, 30, 6, 691).Add(TimeSpan.FromTicks(67)),
                            Name = "Jordan",
                            Price = 450.0,
                            SectionId = 2,
                            StartDate = new DateOnly(2024, 8, 22),
                            StartTime = new TimeOnly(19, 30, 6, 691).Add(TimeSpan.FromTicks(66))
                        },
                        new
                        {
                            TripId = 6,
                            Description = "Syria",
                            EndDate = new DateOnly(2024, 8, 24),
                            EndTime = new TimeOnly(6, 30, 6, 691).Add(TimeSpan.FromTicks(70)),
                            Name = "Jordan",
                            Price = 650.0,
                            SectionId = 2,
                            StartDate = new DateOnly(2024, 8, 15),
                            StartTime = new TimeOnly(22, 30, 6, 691).Add(TimeSpan.FromTicks(69))
                        },
                        new
                        {
                            TripId = 7,
                            Description = "Spain",
                            EndDate = new DateOnly(2024, 8, 24),
                            EndTime = new TimeOnly(6, 30, 6, 691).Add(TimeSpan.FromTicks(74)),
                            Name = "Jordan",
                            Price = 650.0,
                            SectionId = 3,
                            StartDate = new DateOnly(2024, 8, 15),
                            StartTime = new TimeOnly(22, 30, 6, 691).Add(TimeSpan.FromTicks(73))
                        },
                        new
                        {
                            TripId = 8,
                            Description = "USA",
                            EndDate = new DateOnly(2024, 8, 24),
                            EndTime = new TimeOnly(23, 30, 6, 691).Add(TimeSpan.FromTicks(78)),
                            Name = "Jordan",
                            Price = 450.0,
                            SectionId = 3,
                            StartDate = new DateOnly(2024, 8, 22),
                            StartTime = new TimeOnly(19, 30, 6, 691).Add(TimeSpan.FromTicks(77))
                        },
                        new
                        {
                            TripId = 9,
                            Description = "UAE",
                            EndDate = new DateOnly(2024, 8, 24),
                            EndTime = new TimeOnly(6, 30, 6, 691).Add(TimeSpan.FromTicks(82)),
                            Name = "Jordan",
                            Price = 650.0,
                            SectionId = 3,
                            StartDate = new DateOnly(2024, 8, 15),
                            StartTime = new TimeOnly(22, 30, 6, 691).Add(TimeSpan.FromTicks(81))
                        });
                });

            modelBuilder.Entity("Eagle.Models.TripCompany", b =>
                {
                    b.Property<int>("TripCompanyId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TripCompanyId"));

                    b.Property<int>("CompanyId")
                        .HasColumnType("int");

                    b.Property<string>("Responsible")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<int>("TripId")
                        .HasColumnType("int");

                    b.HasKey("TripCompanyId");

                    b.HasIndex("CompanyId");

                    b.HasIndex("TripId");

                    b.ToTable("TripCompany");

                    b.HasData(
                        new
                        {
                            TripCompanyId = 1,
                            CompanyId = 1,
                            Responsible = "Asaad",
                            Status = 0,
                            TripId = 1
                        },
                        new
                        {
                            TripCompanyId = 2,
                            CompanyId = 1,
                            Responsible = "Mohammad",
                            Status = 0,
                            TripId = 2
                        },
                        new
                        {
                            TripCompanyId = 3,
                            CompanyId = 2,
                            Responsible = "Karem",
                            Status = 0,
                            TripId = 4
                        },
                        new
                        {
                            TripCompanyId = 4,
                            CompanyId = 3,
                            Responsible = "Younes",
                            Status = 0,
                            TripId = 9
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);

                    b.HasData(
                        new
                        {
                            Id = "8586ef12-3f99-49ee-80fe-6481fe4343fd",
                            Name = "Admin",
                            NormalizedName = "Admin"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("ProviderKey")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("Name")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("Eagle.Models.Trip", b =>
                {
                    b.HasOne("Eagle.Models.Section", "Section")
                        .WithMany("Trips")
                        .HasForeignKey("SectionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Section");
                });

            modelBuilder.Entity("Eagle.Models.TripCompany", b =>
                {
                    b.HasOne("Eagle.Models.Company", "Company")
                        .WithMany("TripCompanies")
                        .HasForeignKey("CompanyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Eagle.Models.Trip", "Trip")
                        .WithMany("TripCompanies")
                        .HasForeignKey("TripId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Company");

                    b.Navigation("Trip");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Eagle.Models.Company", b =>
                {
                    b.Navigation("TripCompanies");
                });

            modelBuilder.Entity("Eagle.Models.Section", b =>
                {
                    b.Navigation("Trips");
                });

            modelBuilder.Entity("Eagle.Models.Trip", b =>
                {
                    b.Navigation("TripCompanies");
                });
#pragma warning restore 612, 618
        }
    }
}
