// <auto-generated />
using System;
using Eagle.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Eagle.Data.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20240823202407_new3")]
    partial class new3
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Eagle.Models.Section", b =>
                {
                    b.Property<int>("SectionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SectionId"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("SectionId");

                    b.ToTable("tblSection");

                    b.HasData(
                        new
                        {
                            SectionId = 1,
                            Name = "Air Flights"
                        },
                        new
                        {
                            SectionId = 2,
                            Name = "Land Trips"
                        },
                        new
                        {
                            SectionId = 3,
                            Name = "Cruises"
                        });
                });

            modelBuilder.Entity("Eagle.Models.Trip", b =>
                {
                    b.Property<int>("TripId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TripId"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateOnly>("EndDate")
                        .HasColumnType("date");

                    b.Property<TimeOnly>("EndTime")
                        .HasColumnType("time");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<double>("Price")
                        .HasColumnType("float");

                    b.Property<int>("SectionId")
                        .HasColumnType("int");

                    b.Property<DateOnly>("StartDate")
                        .HasColumnType("date");

                    b.Property<TimeOnly>("StartTime")
                        .HasColumnType("time");

                    b.HasKey("TripId");

                    b.HasIndex("SectionId");

                    b.ToTable("tblTrip");

                    b.HasData(
                        new
                        {
                            TripId = 1,
                            Description = "Palastine",
                            EndDate = new DateOnly(2024, 8, 23),
                            EndTime = new TimeOnly(1, 24, 6, 550).Add(TimeSpan.FromTicks(409)),
                            Name = "Jordan",
                            Price = 150.0,
                            SectionId = 1,
                            StartDate = new DateOnly(2024, 8, 18),
                            StartTime = new TimeOnly(18, 24, 6, 550).Add(TimeSpan.FromTicks(401))
                        },
                        new
                        {
                            TripId = 2,
                            Description = "Turky",
                            EndDate = new DateOnly(2024, 8, 23),
                            EndTime = new TimeOnly(1, 24, 6, 550).Add(TimeSpan.FromTicks(415)),
                            Name = "Jordan",
                            Price = 450.0,
                            SectionId = 1,
                            StartDate = new DateOnly(2024, 8, 21),
                            StartTime = new TimeOnly(21, 24, 6, 550).Add(TimeSpan.FromTicks(414))
                        },
                        new
                        {
                            TripId = 3,
                            Description = "Canada",
                            EndDate = new DateOnly(2024, 8, 23),
                            EndTime = new TimeOnly(8, 24, 6, 550).Add(TimeSpan.FromTicks(421)),
                            Name = "Jordan",
                            Price = 650.0,
                            SectionId = 1,
                            StartDate = new DateOnly(2024, 8, 14),
                            StartTime = new TimeOnly(0, 24, 6, 550).Add(TimeSpan.FromTicks(420))
                        },
                        new
                        {
                            TripId = 4,
                            Description = "Iraq",
                            EndDate = new DateOnly(2024, 8, 23),
                            EndTime = new TimeOnly(1, 24, 6, 550).Add(TimeSpan.FromTicks(426)),
                            Name = "Jordan",
                            Price = 150.0,
                            SectionId = 2,
                            StartDate = new DateOnly(2024, 8, 18),
                            StartTime = new TimeOnly(18, 24, 6, 550).Add(TimeSpan.FromTicks(425))
                        },
                        new
                        {
                            TripId = 5,
                            Description = "Palastine",
                            EndDate = new DateOnly(2024, 8, 23),
                            EndTime = new TimeOnly(1, 24, 6, 550).Add(TimeSpan.FromTicks(431)),
                            Name = "Jordan",
                            Price = 450.0,
                            SectionId = 2,
                            StartDate = new DateOnly(2024, 8, 21),
                            StartTime = new TimeOnly(21, 24, 6, 550).Add(TimeSpan.FromTicks(430))
                        },
                        new
                        {
                            TripId = 6,
                            Description = "Syria",
                            EndDate = new DateOnly(2024, 8, 23),
                            EndTime = new TimeOnly(8, 24, 6, 550).Add(TimeSpan.FromTicks(437)),
                            Name = "Jordan",
                            Price = 650.0,
                            SectionId = 2,
                            StartDate = new DateOnly(2024, 8, 14),
                            StartTime = new TimeOnly(0, 24, 6, 550).Add(TimeSpan.FromTicks(435))
                        },
                        new
                        {
                            TripId = 7,
                            Description = "Spain",
                            EndDate = new DateOnly(2024, 8, 23),
                            EndTime = new TimeOnly(8, 24, 6, 550).Add(TimeSpan.FromTicks(442)),
                            Name = "Jordan",
                            Price = 650.0,
                            SectionId = 3,
                            StartDate = new DateOnly(2024, 8, 14),
                            StartTime = new TimeOnly(0, 24, 6, 550).Add(TimeSpan.FromTicks(441))
                        },
                        new
                        {
                            TripId = 8,
                            Description = "USA",
                            EndDate = new DateOnly(2024, 8, 23),
                            EndTime = new TimeOnly(1, 24, 6, 550).Add(TimeSpan.FromTicks(448)),
                            Name = "Jordan",
                            Price = 450.0,
                            SectionId = 3,
                            StartDate = new DateOnly(2024, 8, 21),
                            StartTime = new TimeOnly(21, 24, 6, 550).Add(TimeSpan.FromTicks(446))
                        },
                        new
                        {
                            TripId = 9,
                            Description = "UAE",
                            EndDate = new DateOnly(2024, 8, 23),
                            EndTime = new TimeOnly(8, 24, 6, 550).Add(TimeSpan.FromTicks(453)),
                            Name = "Jordan",
                            Price = 650.0,
                            SectionId = 3,
                            StartDate = new DateOnly(2024, 8, 14),
                            StartTime = new TimeOnly(0, 24, 6, 550).Add(TimeSpan.FromTicks(452))
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);

                    b.HasData(
                        new
                        {
                            Id = "ac8d286c-80ff-4054-9a29-12f5f832cfb1",
                            Name = "Admin",
                            NormalizedName = "Admin"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("ProviderKey")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("Name")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("Eagle.Models.Trip", b =>
                {
                    b.HasOne("Eagle.Models.Section", "Section")
                        .WithMany("Trips")
                        .HasForeignKey("SectionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Section");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Eagle.Models.Section", b =>
                {
                    b.Navigation("Trips");
                });
#pragma warning restore 612, 618
        }
    }
}
